name: "Pull request title update when merging PR"


on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'production_**'
  issue_comment:
    types:
      - created
  pull_request:
    paths:
      - '.github/workflows/build-package.yaml'
      - 'github/scripts/build-package-*'
      - 'github/scripts/get_alation_version.py'
      - 'jenkins/shell/package/**'
      - 'dbin/platform_installer.py'
      - 'deploy/**'
      - 'repo_build/**'
      - 'version.py'
      - 'alation/dependencies/**'
      - 'without_chrootjail/**'
      - 'requirements/**'
      # AL-85657 Require full builds on migration changes
      - 'django/**/migrations/**'
      - 'django-migration/**'
      - 'celery-worker/**'

# Required to read secrets from vault
permissions:
    id-token: write
    packages: write
    contents: write
    issues: write
    checks: write
    pull-requests: write
 
jobs:
  should-package:
      runs-on: ubuntu-latest
      steps:
        #- name: Get PR associated with merge commit sha and suffix alationfc build tag to PR title
        - name: Get PR associated with merge commit sha
          uses: actions/github-script@v6
          id: get_pr
          # Running it only when merge commit is pushed to main/production_ branches
          if: ${{ github.event_name == 'push' && (contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/production_') ) }}
          env: 
            TAG: "1.2.3"
          with:
            result-encoding: string
            script: |
                    const commitSha = '${{ github.sha}}';
                    
                    // Get associated PRs
                    const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    commit_sha: commitSha
                    });
                    console.log(prs)
                    
                    if (prs.data.length > 0) {
                        /*
                        await github.rest.pulls.update({
                            pull_number: prs.data[0].number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            title: `${prs.data[0].title} - alationfc-${process.env.TAG}`
                        })
                        */
                        console.log('Associated PR is '+ prs.data[0].number)
                        return prs.data[0].number; // Return first PR number    
                    }
                    else {
                        console.log('No PRs associated with commit')
                        return '';
                    }
        - name: Create comment
          uses: peter-evans/create-or-update-comment@v4
          if: "${{ steps.get_pr.outputs.result != '' }}"
          env: 
            TAG: "1.2.3"
          with:
            issue-number: "${{steps.get_pr.outputs.result}}"
            body: |
                🎉 This PR is included in alation build --> ${{ env.TAG }} 🎉
            reactions: hooray,rocket


          